@url_dev=http://localhost:3055
@api_key=niggar-api-key
@client_id=68faf8be0aed27e75e01a594
@authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGZhZjhiZTBhZWQyN2U3NWUwMWE1OTQiLCJlbWFpbCI6IndlbHRlcmlhbDIxOEBnbWFpbC5jb20iLCJpYXQiOjE3NjEyNzg4NjYsImV4cCI6MTc2MTQ1MTY2Nn0.v3ypgyhkLNMgfr0TyWiYywA-jWqI9oT7IO6TnpH1oX0
@placeholder_api_key=niggar-api-key
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGZmMDQyYmY1Mzg4NDJiNmRlZjUyMzciLCJlbWFpbCI6ImNvbmNhY0BnbWFpbC5jb20iLCJuYW1lIjoiY29uY2FjIiwiaWF0IjoxNzYxNTQ4OTM1LCJleHAiOjE3NjIxNTM3MzV9.l_f6PkY_IeSIBuJvtgpiBI-J9qSmf3b68Wul1XTusz8

### sign up
POST {{url_dev}}/v1/api/shop/signup
Content-Type: application/json
x-api-key: {{placeholder_api_key}}

{
    "name": "Thai Dinh",
    "email": "welterial@gmail.com",
    "password": "Thaihbvn218"
}

### login
POST {{url_dev}}/v1/api/shop/login
Content-Type: application/json
x-api-key: {{placeholder_api_key}}

{
    "email": "welterial@gmail.com",
    "password": "Thaihbvn218"
}

### logout

POST {{url_dev}}/v1/api/shop/logout
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: {{client_id}}
authorization: {{authorization}}

### refresh token
POST {{url_dev}}/v1/api/shop/refresh-token
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: 68ff042bf538842b6def5237
refreshtoken: {{refresh_token}}