@url_dev=http://localhost:3055
@api_key=niggar-api-key
@clientId=6900378dbddfc4d935b6856b
@authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTAwMzc4ZGJkZGZjNGQ5MzViNjg1NmIiLCJlbWFpbCI6IndlbHRlcmlhbEBnbWFpbC5jb20iLCJuYW1lIjoiVGhhaSBEaW5oIiwiaWF0IjoxNzYxODkyMDk4LCJleHAiOjE3NjMxODgwOTh9.tIvq_t_NT91_N87a1srpYo1FwYLj3jhsGbXWk50u6x0

### Create a new Clothing Product
POST {{url_dev}}/v1/api/product
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

{
    "product_type": "Clothing",
    "product_name": "Stylish T-Shirt v999",
    "product_thumb": "http://example.com/tshirt_stylish.jpg",
    "product_description": "A comfortable and stylish cotton t-shirt.",
    "product_price": 29.99,
    "product_quantity": 69,
    "product_shop": "{{clientId}}",
    "product_attributes": {
        "brand": "UrbanWear",
        "size": "L",
        "material": "Organic Cotton",
        "color": "Black"
    }
}

### Create a new Electronic Product
POST {{url_dev}}/v1/api/product
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

{
    "product_type": "Electronics",
    "product_name": "Smartwatch Pro",
    "product_thumb": "http://example.com/smartwatch_pro.jpg",
    "product_description": "Advanced smartwatch with health tracking.",
    "product_price": 249.99,
    "product_quantity": 75,
    "product_shop": "{{clientId}}",
    "product_attributes": {
        "manufacturer": "FutureTech",
        "model": "SW-Pro-X",
        "warranty": "2 years",
        "features": ["GPS", "Heart Rate Monitor", "Waterproof"]
    }
}

###
GET {{url_dev}}/v1/api/product/drafts/all
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

###
GET {{url_dev}}/v1/api/product/published/all
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### Publish a Product
PATCH {{url_dev}}/v1/api/product/publish/6900b9d05982e6434d9ac272
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### Unpublish a Product
PATCH {{url_dev}}/v1/api/product/unpublish/68ff8ee44f1bf02bfc88a382
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### Search Products
GET {{url_dev}}/v1/api/product/search/Smartwatch
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### FIND ALL PRODUCTS
GET {{url_dev}}/v1/api/product/
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

GET {{url_dev}}/v1/api/product/
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### Find a product
GET {{url_dev}}/v1/api/product/69003a15b67a52859b72fef0
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

### Update a Product
PATCH {{url_dev}}/v1/api/product/69003a15b67a52859b72fef0
x-api-key: {{api_key}}
authorization: {{authorization}}
x-client-id: {{clientId}}
Content-Type: application/json

{
    "product_name": "Updated Stylish T-Shirt",
    "product_price": 39.99,
    "product_attributes": {
        "size": "XL",
        "color": "SEX ROBLOX",
        "brand": "NIGGAR"
    }
}