### Create a new Clothing Product
POST http://localhost:3055/v1/api/product
x-api-key: niggar-api-key
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGZmMDQyYmY1Mzg4NDJiNmRlZjUyMzciLCJlbWFpbCI6ImNvbmNhY0BnbWFpbC5jb20iLCJuYW1lIjoiY29uY2FjIiwiaWF0IjoxNzYxNTU3MDY0LCJleHAiOjE3NjE1NTc5NjR9.dFSjd3SsiWFoSdUFB6vtK_bzEqc_c5uPVxzYz9s0vMg
x-client-id: 68ff042bf538842b6def5237
Content-Type: application/json

{
    "product_type": "Clothing",
    "product_name": "Stylish T-Shirt",
    "product_thumb": "http://example.com/tshirt_stylish.jpg",
    "product_description": "A comfortable and stylish cotton t-shirt.",
    "product_price": 29.99,
    "product_quantity": 200,
    "product_shop": "68ff042bf538842b6def5237",
    "product_attributes": {
        "brand": "UrbanWear",
        "size": "L",
        "material": "Organic Cotton",
        "color": "Black"
    }
}

### Create a new Electronic Product
POST http://localhost:3055/v1/api/product
x-api-key: niggar-api-key
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGZmMDQyYmY1Mzg4NDJiNmRlZjUyMzciLCJlbWFpbCI6ImNvbmNhY0BnbWFpbC5jb20iLCJuYW1lIjoiY29uY2FjIiwiaWF0IjoxNzYxNTU3MDY0LCJleHAiOjE3NjE1NTc5NjR9.dFSjd3SsiWFoSdUFB6vtK_bzEqc_c5uPVxzYz9s0vMg
x-client-id: 68ff042bf538842b6def5237
Content-Type: application/json

{
    "product_type": "Electronics",
    "product_name": "Smartwatch Pro",
    "product_thumb": "http://example.com/smartwatch_pro.jpg",
    "product_description": "Advanced smartwatch with health tracking.",
    "product_price": 249.99,
    "product_quantity": 75,
    "product_shop": "68ff042bf538842b6def5237",
    "product_attributes": {
        "manufacturer": "FutureTech",
        "model": "SW-Pro-X",
        "warranty": "2 years",
        "features": ["GPS", "Heart Rate Monitor", "Waterproof"]
    }
}
